### ISSUE TITLE
Marko support

### ISSUE THREAD

**Issue by Eldar-X** [dsandstrom/atom-double-tag#12]
Hi! How about to add support for marko.js ? Marko also use html like syntax and when change file type to html it's working normally with double tag but we need to using it with marko type.

**Comment by dsandstrom** [comment]
There seems to be bug in the marko-js package, which causes this package to not always to work when the tag has a space after it.  It's missing the right cursor scope.

![marko-double-tag](https://cloud.githubusercontent.com/assets/1400414/23914021/ebabc1d2-08a1-11e7-9cd0-98b918ddaaf3.png)

should be more like

![marko-double-tag-2](https://cloud.githubusercontent.com/assets/1400414/23914074/17905128-08a2-11e7-84fd-08b4f4b390a4.png)
