### ISSUE TITLE
Support for Mustache, HandleBars and Ember HTMLBars

### ISSUE THREAD

**Issue by HodofHod** [dsandstrom/atom-double-tag#18]
[Mustache](http://mustache.github.io/#demo) has tag syntax that looks like this:
> `{{#open-block}}
<span>content</span>
{{/close-block}}`

Mustache templates also include HTML tags. (Mustache also supports "self-closing" tags like so): 

> `{{self-closed}}`

[HandleBars](http://handlebarsjs.com/block_helpers.html) and Ember's HTMLBars are extensions of Mustache which inherit the same block tag style. 

I tried forking and adding support myself, but the hardcoded length offsets (e.g., `endTagRange.start.column + 2` and nested tag logic made it very difficult, especially as I'm unfamiliar with both CoffeeScript and the Atom API.

Thanks!

**Comment by HodofHod** [comment]
Also, Handlebars and HTMLBars both allow using tildes to [control whitespace](http://handlebarsjs.com/expressions.html#whitespace-control) around their tags. The syntax looks like this:

```
{{#each nav ~}}
  <a href="{{url}}">
    {{~#if test}}
      {{~title}}
    {{~^~}}
      Empty
    {{~/if~}}
  </a>
{{~/each}}
```
 Essentially, you can insert a tilde inside the double curly braces on either side. This is optional, so tags may have tildes on one side, both, or none.

**Comment by dsandstrom** [comment]
Can you edit the html tags in a Moustache file?  Like for your example, can you sync edits in the `span` tag?

Are you looking to sync edits in Moustache tags (`{{#open-block}}`) themselves?

**Comment by HodofHod** [comment]
Yes and yes. The best use case for this is custom blocks (rather than the built-in ones like `{{each}}`), which are used extensively in Ember,js, for example.

**Comment by dsandstrom** [comment]
As of now, editing Moustache tags is out of the scope of this package.  However, this package can be forked and edited to change what tags are editable (eg. double-moustache-tag).

You confirmed that you can currently edit html tags in a Moustache file and that is the extent of the scope I can provide.
