### ISSUE TITLE
Mess with self-closed tag inside a tag with the same name

### ISSUE THREAD

**Issue by ruv** [dsandstrom/atom-double-tag#20]
This add-on is affected by [the same bug](https://github.com/atom/bracket-matcher/issues/203) as bracket-matcher regarding self-closed tags.

For example, in the fragment:
``` xml
<div>
  <div /><!-- testcase: try to rename this div into hr -->
</div>
```
If you change the inner `div` to `hr`, the outer `div` end tag will be incorrectly changed.

It seems that the corresponded code is duplicated in many addons. Why don't to have it in some common library?

**Comment by dsandstrom** [comment]
This is fixed by v1.4.1.  When you edit the self-closed tag, the outer tags shouldn't change.  However, the outer tags still don't behave correctly.  When you edit the starting `div`, the ending `div` is not affected.
