### ISSUE TITLE
Need to disable package in order to work

### ISSUE THREAD

**Issue by elton2048** [dsandstrom/atom-double-tag#22]
It is a strange behaviour and I have no idea why the case like this...

When Atom is opened the package has no effect. When the cursor goes to the tag and change it only the tag changes but the other one. However when I disable any package in settings, it works. It still even works if the enable the disabled package again. The only situation it does not work is in initial state. Any idea why this happen? Could it be conflicted with some existing package? (The disabled package does not seem related to this package. I can just disable any package I have installed and it works.)

**Comment by dsandstrom** [comment]
Does it work if you open a new file after you open Atom?

**Comment by elton2048** [comment]
Yup it works if open a new untitled file.

**Comment by dsandstrom** [comment]
It may have problems operating on already open files after first installing.  However, I've never experienced anything like that and can't reproduce it.  Hopefully, it's just a minor glitch and works fine in the future.  Please let me know if you continue to have problems.

**Comment by dsandstrom** [comment]
Let me know if this is still a problem.
