### ISSUE TITLE
Doesn't activate when typing on end tag

### ISSUE THREAD

**Issue by seanmars** [dsandstrom/atom-double-tag#3]
On start tag is work fine, but end tag is not working.

**Comment by dsandstrom** [comment]
Thanks.  I haven't added support for this, but it seems like it would be useful.

**Comment by sunabozu** [comment]
Any news on this feature?

**Comment by rkrv** [comment]
Just installed this package, very happy with it, but really miss this feature.

**Comment by dsandstrom** [comment]
Added in v0.9.0.
