### ISSUE TITLE
double-tag not working 

### ISSUE THREAD

**Issue by raini35** [dsandstrom/atom-double-tag#35]
So I've installed double-tag but it's not working on current and new files. I'm working with Atom - 1.24.0. Not quite sure what the problem is. 
![tzuuiogp4v](https://user-images.githubusercontent.com/13359863/37243833-766a5eea-2445-11e8-8121-4aa5d684ab0f.gif)

**Comment by dsandstrom** [comment]
Same issue as #27 or doesn't work at all for you?  I suggest saving the file and restarting atom, then try again.

**Comment by raini35** [comment]
In that example, I restarted at least 3 times and reinstalled the package and the test.html already existed, but it still wasn't working. For some reason tho, after I put text inside the div it suddenly started working. I have no clue. Thanks for reply! @dsandstrom

**Comment by dsandstrom** [comment]
I'm not sure what went wrong.  Hopefully, it was just a hiccup.  Going to close this issue, please let me know if this problem continues.

**Comment by dreadrocksean** [comment]
Still doesnt work for me.  I'm using it in React

**Comment by HumidBrains** [comment]
It doesn't work for me either. Restarts and saves multiple times, but it's completely dead.
