### ISSUE TITLE
No longer working with Laravel Blade files

### ISSUE THREAD

**Issue by MichaelIshri** [dsandstrom/atom-double-tag#39]
Hi,

Just a heads up, that Double Tag was working with Laravel's blade template language (for HTML tags) but it's now stopped working now. 

Blade files are simply HTML files with the addition of some template directives that begin with an "@" symbol. I don't believe updating the matching directive was working before but certainly updating HTML tags was.

The file extension of a blade file is "filename.blade.php".

Here's a link to the doco: [https://laravel.com/docs/5.6/blade](https://laravel.com/docs/5.6/blade) if you need it.

I think it'd be a matter of making blade files recognised as HTML rather than any extra work to support the blade syntax. 

Let me know if you need any more info.

Thank you, and great work on this extension. :-)

**Comment by MichaelIshri** [comment]
I'm sorry, didn't see that you'd responded. :-/

Right, I did see the option to add the "Enabled Scopes" option, is that what you mean? I tried the suggested but it didn't seem to work. 

How do I find out what the syntax/scope?

I'm using, https://atom.io/packages/language-blade.

**Comment by MichaelIshri** [comment]
Oh, I think I got the scope from https://github.com/jawee/language-blade/blob/master/grammars/blade.cson

I've added "text.html.php.blade" but doesn't look to be working.

**Comment by MichaelIshri** [comment]
Doh! Nevermind, it is infact working, I was testing on an ignored tag (<title>). My bad, :-( 

Thanks for the help. :-)

**Comment by dsandstrom** [comment]
@MichaelIshri To confirm, what did you add to the "Enabled Scopes"?  Maybe I can add it to the defaults.

**Comment by MichaelIshri** [comment]
Sorry, should've mentioned, could be helpful to others. I added: `text.html.php.blade` to the **Enabled Scopes** list. 

So my list now looks like:

`text.html, text.html.basic, text.xml, text.marko, source.js.jsx, source.tsx, text.html.erb, text.html.php, text.html.php.blade`

**Comment by dsandstrom** [comment]
Added to default
