### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by dmnd** [dsandstrom/atom-double-tag#4]
This works great in an HTML file. Can you enable it for [Javascript (JSX)](https://github.com/orktes/atom-react) too?

**Comment by dsandstrom** [comment]
Should be possible. I'm not familiar with jsx, can you provide an example
file?

**Comment by dmnd** [comment]
Sure, [here's an example](https://github.com/facebook/react/blob/master/examples/quadratic/example.js).

**Comment by dmnd** [comment]
Awesome, thanks @dsandstrom! ❤️
