### ISSUE TITLE
Don't work in .isml format

### ISSUE THREAD

**Issue by Unikalx** [dsandstrom/atom-double-tag#41]
In .html format work. I add .isml format in Enabled Scopes but he did not start work. Is there any way to include it?

**Comment by dsandstrom** [comment]
I'm not familiar with that language, what Atom package are you using for the language syntax?

**Comment by Unikalx** [comment]
I using [language-demandware](https://atom.io/packages/language-demandware), .isml very similar to .html but have the custom tags

**Comment by dsandstrom** [comment]
Try adding `text.isml` https://github.com/kenwheeler/language-demandware/blob/5bc91a7c26e279c09e8144336f0445681a4ac817/grammars/isml.cson#L531

**Comment by Unikalx** [comment]
Working =)
I add in Enabled Scopes `text.html.basic text.isml` and double tag start work.

Thanks!
