### ISSUE TITLE
Not working on Atom 1.31.1?

### ISSUE THREAD

**Issue by AxDSan** [dsandstrom/atom-double-tag#45]
Having this issue.

![](https://i.imgur.com/X6H5S4u.gif)

How to reproduce:

- Download latest Atom
- Work on some files.
- Install the package
- Try to change a tag; It won't update.

Also I need a little help understanding what's up with the scope thing?
I thought that this would automatically look up for changes in tags in HTML or any other, but what does it really means? do I have to have a file named `text.html`?

**Comment by dsandstrom** [comment]
People have reported that this doesn't work on new files, but I can't really reproduce.  Did you restart Atom after installing this package?

If you are working on html and erb files, you don't need to add anything to the scope settings.  The reason it's not enabled for all files is to not degrade performance unnecessarily.  I'm not sure if this works natively on Django files, I don't have any experience. However, you can add it's scope to the package's settings.  See #44 for more info.

**Comment by AxDSan** [comment]
> 
> 
> People have reported that this doesn't work on new files, but I can't really reproduce. Did you restart Atom after installing this package?
> 
> If you are working on html and erb files, you don't need to add anything to the scope settings. The reason it's not enabled for all files is to not degrade performance unnecessarily. I'm not sure if this works natively on Django files, I don't have any experience. However, you can add it's scope to the package's settings. See #44 for more info.

Yes I have tested it in every way possible, uninstalling, reinstalling, closing the editor, opening it back up, and nothing... here's a gif showing:

![](https://i.imgur.com/Nopyztz.gif)

**Comment by dsandstrom** [comment]
Does it work if the syntax is straight "HTML".  Please try on an HTML file, not a Django file.  My theory is you need to add the right syntax string to the settings.

**Comment by AxDSan** [comment]
It Works!

![](https://i.imgur.com/yQcCmbp.gifv)

I created a pure HTML file and changed the syntax in the syntax selector and viola!
___

Hmm, now... how do I add django html files? or that's something you have to work on?

**Comment by dsandstrom** [comment]
Sweet, thanks for following up.

There is no inherit support for Django, you will have to add the syntax string to the package's settings.  The documentation is lacking for this, but #44 has a bit more info.

Please let me know what string works so I can add it to the package for future Django users.
