### ISSUE TITLE
Custom tags in JSX files don't sync

### ISSUE THREAD

**Issue by dmnd** [dsandstrom/atom-double-tag#47]
I think JSX support has regressed since tree-sitter came along. Here's a representative JSX file:

```js
import React from "react";

function App({ title, children }) {
  return <div title={title}>children</div>;
}

React.render(<App title="hi">hello</App>, document.getElementById("app"));
```

Double tag works fine if I edit the `<div>` tag. But it doesn't work for the `<App>` tag. @dsandstrom based on your https://github.com/dsandstrom/atom-double-tag/issues/46#issuecomment-449154990 I think it's because the `<App>` tag doesn't have `entity.name.tag`.

#### `<App>` scope info

Scopes at Cursor: `source.js`, `meta.class.component.jsx`

Syntax tree at Cursor:
* source.js
* program
* expression_statement
* call_expression
* arguments
* jsx_element
* jsx_opening_element
* identifier

#### `<div>` scope info

Scopes at Cursor: `source.js`, `entity.name.tag`
Syntax tree at Cursor: 
* source.js
* program
* function
* statement_block
* return_statement
* jsx_element
* jsx_opening_element
* identifier

**Comment by dsandstrom** [comment]
In case you are still in need, what syntax package are you using for jsx?

**Comment by dsandstrom** [comment]
Try out this one: https://atom.io/packages/react
It provides `entity.name.tag.js` scope, so double-tag works.

**Comment by dmnd** [comment]
Sorry, I ended up moving to VS Code, so I don't remember.
