### ISSUE TITLE
Doesn't support dashes

### ISSUE THREAD

**Issue by Bouzmine** [dsandstrom/atom-double-tag#5]
I'm using Angular so dashes in HTML tags are common, however this package doesn't work when editing tags with dashes.

**Comment by dander401** [comment]
by not supporting dashes... im seeing it actually strip them off of the second tag to create mismatched tags.

**Comment by Bouzmine** [comment]
That's what I'm talking about.

**Comment by dsandstrom** [comment]
I'm not familiar with Angular, can you provide an example file?

**Comment by dander401** [comment]
Not just angular but any framework or library with custom tags. Sorry I'm on my phone so please forgive proper formating. Try these this tag.

<my-tag></my-tag>

**Comment by dsandstrom** [comment]
Try latest release, hopefully it's fixed.

**Comment by Bouzmine** [comment]
It works, thanks!
